name: iceberg-auth-demo
on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    paths:
      - 'iceberg-auth/**'
      - '.github/workflows/_common_jobs.yml'
      - '.github/workflows/ci_iceberg_auth_demo.yml'
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      workspace: iceberg-auth
