name: icebird-grep-demo
on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    paths:
      - 'icebird-grep/**'
      - '.github/workflows/_common_jobs.yml'
      - '.github/workflows/ci_icebird_grep_demo.yml'
jobs:
  ci:
    uses: ./.github/workflows/_common_jobs.yml
    with:
      workspace: icebird-grep
